config/routes.rb
Rails.application.routes.draw do
  resources :service_packages
  get "reports/monthly_income_report"

  resources :clients do
    resources :invoices do
      resources :payments
    end
    resources :tickets
  end

  get "all_invoices", to: "invoices#general_index"

  devise_for :users

  get "servicios", to: "statics#services"
  get "preguntas_frecuentes", to: "statics#frequent_questions"
  get "contáctanos", to: "statics#contact"
  get "nosotros", to: "statics#about_us"

  get "inicio", to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :client
  belongs_to :service_package
  has_many :payments, dependent: :destroy

  validates :started_at, presence: { message: "no puede estar vacio" }
  validates :disconnected_at, presence: { message: "no puede estar vacio" }
  validates :finished_at, presence: { message: "no puede estar vacio" }

  scope :active, -> { where(finished_at: Time.current..) }
  scope :unpaid, -> { where.not(payment_status: "paid") }
  scope :showing, -> { active.or(unpaid) }

  before_save :update_payment_status

  state_machine :payment_status, initial: :pending do
    state :pending
    state :partially_paid
    state :paid

    event :add_payment do
      transition [:pending, :partially_paid] => :partially_paid, if: ->(invoice) { invoice.total_payments > 0 && invoice.total_payments < invoice.total_bill }
      transition [:pending, :partially_paid] => :paid, if: ->(invoice) { invoice.total_payments >= invoice.total_bill }
    end
    event :remove_payment do
      transition [:paid, :partially_paid] => :partially_paid, if: ->(invoice) { invoice.total_payments > 0 && invoice.total_payments < invoice.total_bill }
      transition [:paid, :partially_paid] => :pending, if: ->(invoice) { invoice.total_payments <= 0 }
    end
  end

  def total_payments
    payments.sum(:amount)
  end

  def set_payment_status
    add_payment
  end

  def reset_payment_status
    remove_payment
  end

  def update_payment_status
    if total_payments >= total_bill
      self.payment_status = "paid" unless payment_status == "paid "
    elsif total_payments > 0
      self.payment_status = "partially paid" unless payment_status == "partially paid"
    else
      self.payment_status = "pending" unless payment_status == "pending"
    end
  end

  def payment_status_in_spanish
    snake_payment_status = payment_status.gsub(" ", "_")
    I18n.t("activerecord.attributes.invoice.payment_statuses.#{snake_payment_status}")
  end

  def active?
    Time.current < finished_at
  end

  def unpaid?
    payment_status != "paid"
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, except: :general_index
  before_action :set_invoice, only: %i[show edit update destroy]

  # This acction filters any invoice using its attributes
  def general_index
    @all_invoices = Invoice.all

    if params[:start_date].present? && params[:end_date].present?
      start_date = Date.parse(params[:start_date]).beginning_of_day
      end_date = Date.parse(params[:end_date]).end_of_day
      @all_invoices = @all_invoices.where(started_at: start_date..end_date)
    end

    if params[:payment_status].present?
      @all_invoices = @all_invoices.where(payment_status: params[:payment_status].gsub("_", " "))
    end

    if params[:service_package_name].present?
      @all_invoices = @all_invoices.where(service_package_name: params[:service_package_name])
    end

    if params[:name].present?
      @all_invoices = @all_invoices.joins(:client).where("LOWER(clients.name) LIKE ?", "%#{params[:name].downcase}%")
    end

    @all_invoices = @all_invoices.order(started_at: :desc)
  end

  # GET /invoices or /invoices.json
  def index
    @invoices = @client.invoices.all
  end

  # GET /invoice/1 or /invoice/1.json
  def show
  end

  # GET /invoice/new
  def new
    @invoice = @client.invoices.new
    @service_package_selected = ServicePackage.find_by(name: "Sin Definir").id
  end

  # POST /invoice or /invoice.json
  def create
    @invoice = @client.invoices.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to client_url(@client, anchor: "invoice"), notice: "La factura fue creada correctamente." }
        format.json { render :show, status: :created, location: [@client, @invoice] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /invoice/1/edit
  def edit
    @service_package_selected = @invoice.service_package.id
  end

  # PATCH/PUT /invoice/1 or /invoice/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to client_url(@client), notice: "La factura fue modificada correctamente." }
        format.json { render :show, status: :ok, location: [@client, @invoice] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice/1 or /invoice/1.json
  def destroy
    @invoice.destroy!

    respond_to do |format|
      format.html { redirect_to client_url(@client), notice: "La factura fue eliminada correctamente." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:client_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_invoice
    @invoice = @client.invoices.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def invoice_params
    params.require(:invoice).permit(
      :service_package_name,
      :service_package_cost,
      :started_at,
      :disconnected_at,
      :finished_at,
      :additional_concept,
      :aditional_amount,
      :total_bill,
      :payment_status,
      :notes,
      :client_id,
      :service_package_id
    )
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def service_package_options
    ServicePackage.all.map do |service_package|
      [
        service_package.name,
        service_package.id,
        { data: { name: service_package.name, cost: service_package.price } }
      ]
    end
  end

  def service_package_names
    Invoice.distinct.pluck(:service_package_name).compact
  end

  def payment_status_options
    Invoice.state_machine.states.map do |state|
      [I18n.t("activerecord.attributes.invoice.payment_statuses.#{ state.name }"), state.name]
    end
  end
end

app/views/invoices/_form.html.erb
<div class="col-4 mb-3">
  <%= form_with(model: [@client, @invoice]) do |f| %>
    <% if @invoice.errors.any? %>
      <div class="text-danger">
        <h2> Se han producido los siguientes errores: </h2>
        <ul>
          <% @invoice.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :service_package_id, "Paquete de servicio", class: "form-label" %>
    <%= f.select :service_package_id,
      options_for_select(service_package_options, @service_package_selected),
      {},
      class: "form-control mb-3",
      id: "service_package_select" %>

    <%= f.hidden_field :service_package_name, class: "form-control mb-3", id: "service_package_name" %>

    <%= f.label :service_package_cost, "Costo del paquete", class: "form-label" %>
    <%= f.number_field :service_package_cost, class: "form-control mb-3", id: "service_package_cost", readonly: true %>

    <%= f.label :started_at, "Fecha de inicio", class: "form-label" %>
    <%= f.date_field :started_at, class: "form-control mb-3" %>

    <%= f.label :disconnected_at, "Fecha límite de pago", class: "form-label" %>
    <%= f.date_field :disconnected_at, class: "form-control mb-3" %>

    <%= f.label :finished_at, "Fecha de corte", class: "form-label" %>
    <%= f.date_field :finished_at, class: "form-control mb-3" %>

    <%= f.label :additional_concept, "Concepto adicional", class: "form-label" %>
    <%= f.text_field :additional_concept, class: "form-control mb-3" %>

    <%= f.label :aditional_amount, "Monto adicional", class: "form-label" %>
    <%= f.number_field :aditional_amount, class: "form-control mb-3", id: "aditional_amount" %>

    <%= f.label :notes, "Anotaciones", class: "form-label" %>
    <%= f.text_area :notes, class: "form-control mb-3" %>

    <%= f.label :total_bill, "Monto total", class: "form-label" %>
    <%= f.number_field :total_bill, class: "form-control mb-3", id: "total_bill", readonly: true %>

    <%= f.hidden_field :payment_status, class: "form-control mb-3", readonly: true%>

    <button type="submit" class="btn btn-primary"><%= yield(:button) %></button>
  <% end %>
</div>

app/views/invoices/edit.html.erb
<div class= "container">
  <div class="row justify-content-center">
    <div class="col-4">
        <h2>Editar Servicio</h2>
    </div>
  </div>

  <div class="row justify-content-center">
    <%= provide(:button, "Editar") %>
    <%= render "invoices/form" %>
  </div>
</div>

app/views/invoices/general_index.html.erb
<div class="container-fluid">
  <div class="row mb-3">
    <div class="col-4">
      <h2>Listado de Servicios</h2>
    </div>
  </div>

  <%= form_with(url: all_invoices_path, method: :get, local: true) do %>
    <div class="row my-3">
      <div class="col-2">
        <%= label_tag :name, "Nombre", class: "form-label " %>
        <%= text_field_tag :name, params[:name], class: "form-control " %>
      </div>

      <div class="col-2">
        <%= label_tag :service_package_name, "Paquete de servicios", class: "form-label "  %>
        <%= select_tag :service_package_name,
          options_for_select(service_package_names, params[:service_package_name]),
          prompt: "Seleccionar",
          class: "form-control " %>
      </div>

      <div class="col-2">
        <%= label_tag :start_date, "Fecha de inicio", class: "form-label"  %>
        <%= date_field_tag :start_date, params[:start_date], class: "form-control" %>
      </div>

      <div class="col-2">
        <%= label_tag :end_date, "Fecha de fin", class: "form-label"  %>
        <%= date_field_tag :end_date, params[:end_date], class: "form-control" %>
      </div>

      <div class="col-2">
        <%= label_tag :payment_status, "Estado de pago", class: "form-label"  %>
        <%= select_tag :payment_status,
          options_for_select(payment_status_options, params[:payment_status]),
          prompt: "Seleccionar",
          class: "form-control" %>
      </div>

      <div class="col-2">
        <%= submit_tag "Filtrar", class: "btn btn-primary" %>
        <%= link_to "Generar Reporte", reports_monthly_income_report_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <table class="table table-secondary table-hover table-responsive table-striped">
    <thead>
      <tr>
        <th scope="col">Cliente</th>
        <th scope="col">Servicio</th>
        <th scope="col">Fecha de inicio</th>
        <th scope="col">Fecha límite de Pago</th>
        <th scope="col">Fecha de Corte</th>
        <th scope="col">Estado de factura</th>
        <th scope="col">Facturación total</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @all_invoices.each do |invoice| %>
        <tr>
          <th scope="row"><%= invoice.client.name %></th>
          <td><%= invoice.service_package.name %></td>
          <td><%= invoice.started_at.to_fs(:short) %></td>
          <td><%= invoice.disconnected_at.to_fs(:short) %></td>
          <td><%= invoice.finished_at.to_fs(:short) %></td>
          <td><%= invoice.payment_status_in_spanish %></td>
          <td><%= number_to_currency invoice.total_bill %></td>
          <td>
            <%= link_to "Ver Factura",
                  client_invoice_path(invoice.client, invoice),
                  class: "link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/invoices/index.html.erb
<div class="container-fluid ms-3">
  <div class="row mb-3">
    <div class="col-4">
      <h2>Historial de Facturas de <%= @client.name %></h2>
    </div>
  </div>
</div>

<table class="table table-secondary table-hover table-responsive table-striped">
  <thead>
    <tr>
      <th scope="col">Servicio</th>
      <th scope="col">Fecha de inicio</th>
      <th scope="col">Fecha límite de Pago</th>
      <th scope="col">Fecha de Corte</th>
      <th scope="col">Concepto adicional</th>
      <th scope="col">Monto adicional</th>
      <th scope="col">Estado de factura</th>
      <th scope="col">Facturación total</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <th scope="row"><%= invoice.service_package.name %></th>
        <td><%= invoice.started_at.to_fs(:short) %></td>
        <td><%= invoice.disconnected_at.to_fs(:short) %></td>
        <td><%= invoice.finished_at.to_fs(:short) %></td>
        <td><%= invoice.additional_concept %></td>
        <td><%= number_to_currency invoice.aditional_amount %></td>
        <td><%= invoice.payment_status_in_spanish %></td>
        <td><%= number_to_currency invoice.total_bill %></td>
        <td>
          <%= link_to "Ver Factura",
                client_invoice_path(invoice.client, invoice),
                class: "link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/new.html.erb
<div class= "container">
  <div class="row justify-content-center">
    <div class="col-4">
        <h2>Nuevo Servicio</h2>
    </div>
  </div>

  <div class="row justify-content-center">
    <%= provide(:button, "Crear") %>
    <%= render "invoices/form" %>
  </div>
</div>

app/views/invoices/show.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-6">
      <h2>Factura</h2>
    </div>

    <div class="col-6 text-end">
      <div class="btn-group">
        <%= link_to "Regresar al Servicio", client_path(@client, anchor: "invoice"), class: "btn btn-outline-light rounded-end me-3" %>
        <%= link_to "Realizar pago", new_client_invoice_payment_path(@client, @invoice), class: "btn btn-outline-light rounded me-3" %>
        <%= link_to "index de pagos", client_invoice_payments_path(@client, @invoice), class: "btn btn-outline-light rounded-start" %>
      </div>
    </div>
  </div>

  <table class="table table-secondary table-hover table-responsive table-striped">
    <thead>
      <tr class="text-center">
        <th scope="col" colspan="2">Detalle de Facturación</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row" class="ps-5">Cliente</th>
        <td><%= @invoice.client.name %></td>
      </tr>
      <tr>
        <th scope="row" class="ps-5">Servicio</th>
        <td><%= @invoice.service_package.name %></td>
      </tr>
      <tr>
        <th scope="row" class="ps-5">Fecha de inicio</th>
        <td><%= @invoice.started_at.to_fs(:short) %></td>
      </tr>
      <tr>
        <th scope="row" class="ps-5">Fecha límite de Pago</th>
        <td><%= @invoice.disconnected_at.to_fs(:short) %></td>
      </tr>
      <tr>
        <th scope="row" class="ps-5">Fecha de Corte</th>
        <td><%= @invoice.finished_at.to_fs(:short) %></td>
      </tr>
      <tr>
        <th scope="row" class="ps-5">Concepto adicional</th>
        <td><%= @invoice.additional_concept %></td>
      </tr>
      <tr>
        <th scope="row" class="ps-5">Monto adicional</th>
        <td><%= @invoice.aditional_amount %></td>
      </tr>
      <tr>
        <th scope="row" class="ps-5">Estado de factura</th>
        <td><%= @invoice.payment_status_in_spanish %></td>
      </tr>
      <tr>
        <th scope="row" class="ps-5">Facturación total</th>
        <td><%= @invoice.total_bill %></td>
      </tr>
    </tbody>
  </table>
</div>