config/routes.rb
Rails.application.routes.draw do
  resources :service_packages
  get "reports/monthly_income_report"

  resources :clients do
    resources :invoices do
      resources :payments
    end
    resources :tickets
  end

  get "all_invoices", to: "invoices#general_index"

  devise_for :users

  get "servicios", to: "statics#services"
  get "preguntas_frecuentes", to: "statics#frequent_questions"
  get "contáctanos", to: "statics#contact"
  get "nosotros", to: "statics#about_us"

  get "inicio", to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/views/shared/_footer.html.erb
<footer id="footer" class="mt-auto">
  <div class="row text-center">
    <div class="col-12 col-md">
      <%# link_to "", %> link
    </div>
    <div class="col-12 col-md">
      <%# link_to "", %> link
    </div>
    <div class="col-12 col-md">
      <%# link_to "", %> link
    </div>
    <div class="col-12 col-md">
      <%= link_to "Soy administrador", clients_path%>
    </div>
  </div>  
</footer>

app/views/shared/_header.html.erb
<nav id="header" class="navbar navbar-expand-md navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/inicio">
      <%= image_tag asset_path("logo_orion.jpeg"), id: "Logo_orion", alt: "Logo_orion" %>
      <strong>Orión Networks</strong>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "inicio", root_path, class: "nav-link", aria: {current: "page"} %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Servicios
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/inicio#residential">Todos los servicios</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="servicios">Residenciales</a></li>
            <li><a class="dropdown-item" href="servicios">Empresariales</a></li>
            <li><a class="dropdown-item" href="servicios">Dedicado de alta capacidad</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="preguntas_frecuentes">Preguntas Frecuentes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="cont%C3%A1ctanos">Contáctanos</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_users_heade.html.erb
<nav id="header" class="navbar navbar-expand-md navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="inicio">
      <%= image_tag asset_path("logo_orion.jpeg"), id: "Logo_orion", alt: "Logo_orion" %>
      <strong>Orión Networks</strong>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="inicio">Inicio</a>
        </li>
        <li class="nav-item">
          <%= link_to "Iniciar sesión", new_user_session_path, class: "navlink"%>
        </li>
        <li class="nav-item">
          <%= link_to "Registrarme", new_user_registration_path, class: "navlink"%>
        </li>
        <li class="nav-item">
          <%= link_to "Editar autor", edit_autor_registration_path, class: "navlink"%>        </li>
        <li class="nav-item">
          <%= button_to "Cerrar sesión", destroy_autor_session_path, class: "navlink", method: :delete, data: { confirm: "Are you sure to delete?" }%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_users_header.html.erb
<nav id="header" class="navbar navbar-expand-md navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/inicio">
      <%= image_tag asset_path("logo_orion.jpeg"), id: "Logo_orion", alt: "Logo_orion" %>
      <strong>Orión Networks</strong>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Clientes", clients_path, class: "nav-link", aria: {current: "page"} %>
        </li>
        <li class="nav-item">
            <%= link_to "Servicios", all_invoices_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Paquetes", service_packages_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to "Cerrar sesión", destroy_user_session_path, class: "nav-link", method: :delete, data: { confirm: "Are you sure to delete?" }%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>