config/routes.rb
Rails.application.routes.draw do
  resources :service_packages
  get "reports/monthly_income_report"

  resources :clients do
    resources :invoices do
      resources :payments
    end
    resources :tickets
  end

  get "all_invoices", to: "invoices#general_index"

  devise_for :users

  get "servicios", to: "statics#services"
  get "preguntas_frecuentes", to: "statics#frequent_questions"
  get "contáctanos", to: "statics#contact"
  get "nosotros", to: "statics#about_us"

  get "inicio", to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :invoices, dependent: :destroy
  has_many :tickets, dependent: :destroy
  validates :name, presence: { message: "no puede estar vacio" }
  validates :phone, presence: { message: "no puede estar vacio" }
  validates :location, presence: { message: "no puede estar vacio" }

  def status
    active ? "Activo" : "Inactivo"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: %i[show edit update destroy]

  # GET /clients or /clients.json
  def index
    @clients = Client.all.order(created_at: :desc)
  end

  # GET /client/1 or /client/1.json
  def show
    @invoices = @client.invoices.order(created_at: :desc)
    @tickets = @client.tickets
  end

  # GET /client/new
  def new
    @client = Client.new
  end

  # GET /client/1/edit
  def edit
  end

  # POST /client or /client.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Cliente creado correctamente." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client/1 or /client/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "El cliente ha sido actualizado correctamente." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client/1 or /client/1.json
  def destroy
    @client.destroy!

    respond_to do |format|
      format.html { redirect_to service_packages_url, notice: "Cliente eliminado correctamente" }
      format.json { head :no_content }
    end
  end

  private
  # Only allow a list of trusted parameters through.
  def client_params
    params.require(:client).permit(:name, :active, :phone, :location)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="col-4 mb-3">
  <%= form_with(model: client) do |f| %>
    <% if client.errors.any? %>
      <div class="text-danger">
        <h2>Se han producido los siguientes errores: </h2>
        <ul>
          <% client.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :name, "Nombre", class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %><br>

    <%= f.label :active, "Activo", class: "form-check-label" %><br>
    <%= f.check_box :active, class: "form-check-input mb-3" %><br>

    <%= f.label :phone, "Teléfono", class: "form-label" %>
    <%= f.text_field :phone, class: "form-control" %><br>

    <%= f.label :location, "Localidad", class: "form-label" %>
    <%= f.text_field :location, class: "form-control" %><br>

    <button type="submit" class="btn btn-primary"><%= yield(:button) %></button>
  <% end %>
</div>

app/views/clients/edit.html.erb
<div class= "container">
  <div class="row justify-content-center">
    <div class="col-4">
        <h2>Editar Cliente</h2>
    </div>
  </div>

  <div class="row justify-content-center">
    <% provide(:button, "Editar") %>
    <%= render "form", client: @client %>
  </div>
</div>

app/views/clients/index.html.erb
<div class="container-fluid ms-3">
  <div class="row mb-3">
    <div class="col-10">
      <h2>Listado de clientes</h2>
    </div>
    <div class="col-2">
      <%= link_to "Nuevo cliente", new_client_path, class: "btn btn-outline-light" %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <table class="table table-secondary table-hover table-responsive table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Status</th>
        <th scope="col">Teléfono</th>
        <th scope="col">Localidad</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <th scope="row"> <%= client.id %><br></th>
          <td>
            <%= link_to client.name,
                  client,
                  class: "link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
          </td>
          <td><%= client.active ? "Activo" : "Inactivo" %></td>
          <td><%= client.phone %></td>
          <td><%= client.location %></td>
          <td>
            <div class="btn-group">
              <%= link_to "Editar",
                    edit_client_path(client),
                    class: "btn btn-outline-secondary rounded-end me-2" %>
              <%= button_to "Eliminar",
                    client,
                    class: "btn btn-outline-danger",
                    method: :delete,
                    data: { turbo_confirm: "¿Seguro que quieres eliminar este Cliente?" } %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clients/new.html.erb
<div class= "container">
  <div class="row justify-content-center">
    <div class="col-4">
        <h2>Nuevo Cliente</h2>
    </div>
  </div>

  <div class="row justify-content-center">
    <% provide(:button, "Crear") %>
    <%= render "form", client: @client %>
  </div>
</div>

app/views/clients/serv.html.erb
<div class= "container-fluid ms-3">
  <div class="row mb-3">
    <div class="col-4">
        <h2>Listado de Servicios</h2>
    </div>
  </div>
</div>

<table class="table table-secondary table-hover table-responsive table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Fecha_inicio</th>
      <th scope="col">Fecha_corte</th>
      <th scope="col">Fecha_límite</th>
      <th scope="col">Costo</th>
      <th scope="col">Fecha_pago</th>
      <th scope="col">Anotaciones</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @services.each do |service| %>
      <tr>
        <th scope="row"> <%= service.id %></th>
        <td><%= service.name %></td>
        <td><%= service.started_at %></td>
        <td><%= service.finished_at %></td>
        <td><%= service.disconnected_at %></td>
        <td><%= service.price %></td>
        <td><%= service.paid_at %></td>
        <td><%= service.notes %></td>
        <td><%# link_to "ver servicio", edit_client_path(client) %>
            <%= link_to @clients.find(service.client_id).name, client_path(service.client_id), class: "link-dark"  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/show.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col-6">
      <h2>Cliente</h2>
    </div>

    <div class="col-6 text-end">
      <%= button_to "Eliminar cliente",
            @client,
            class: "btn btn-outline-danger",
            method: :delete,
            data: { turbo_confirm: "¿Seguro que quieres eliminar este Cliente?" } %>
    </div>
  </div>

  <div class="card bg-black text-secondary mb-5">
    <h3 class="card-header"><%= @client.name %></h3>
    <div class="card-body row">
      <p class="card-text">Status: <strong><%= @client.status %></strong></p>
      <p class="card-text">Teléfono: <strong><%= @client.phone %></strong></p>
      <p class="card-text">Localidad: <strong><%= @client.location %></strong></p>
      <div class="col-6">
        <%= link_to "Editar cliente", edit_client_path(@client), class: "btn btn-outline-secondary" %>
      </div>
    </div>
  </div>

  <div class="row my-5">
    <div class="col-6">
      <h2>Servicios Activos</h2>
    </div>

    <div class="col-6 text-end">
      <div class="btn-group">
      <%= link_to "Historial de Facturas",
            client_invoices_path(@client),
            class: "btn btn-outline-light rounded-end me-3" %>
      <%= link_to "Nuevo servicio",
            new_client_invoice_path(@client, @invoice),
            class: "btn btn-outline-light rounded-start" %>
      </div>
    </div>
  </div>

  <% @invoices.showing.each do |invoice| %>
    <div class="card bg-black text-secondary mb-5" id="invoice_<%= invoice.id %>">
      <h3 class="card-header">
        <%= link_to invoice.service_package.name,
              client_invoice_path(@client, invoice),
              class: "link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
      </h3>
      <div class="card-body row">
        <p class="card-text">
          Costo de Paquete de Servicio:
          <strong><%= number_to_currency invoice.service_package_cost %></strong>
        </p>
        <p class="card-text">
          Fecha de inicio:
          <strong><%= invoice.started_at.to_fs(:long) %></strong>
        </p>
        <p class="card-text">
          Fecha límite de pago:
          <strong><%= invoice.disconnected_at.to_fs(:long) %></strong>
        </p>
        <p class="card-text">
          Fecha de corte:
          <strong><%= invoice.finished_at.to_fs(:long) %></strong>
        </p>
        <p class="card-text">
          Concepto adicional:
          <strong><%= invoice.additional_concept %></strong>
        </p>
        <p class="card-text">
          Monto adicional:
          <strong><%= number_to_currency invoice.aditional_amount %></strong>
        </p>
        <p class="card-text">
          Monto total:
          <strong><%= number_to_currency invoice.total_bill %></strong>
        </p>
        <p class="card-text">
          Estado de Factura:
          <strong><%= invoice.payment_status_in_spanish %></strong>
        </p>
        <p class="card-text">
          Anotaciones:
          <strong><%= invoice.notes %> </strong>
        </p>
        <div class="col-6">
          <%= link_to "Editar servicio",
                edit_client_invoice_path(@client, invoice),
                class: "btn btn-outline-secondary" %>
        </div>
        <div class="col-6 text-end">
          <%= button_to "Eliminar servicio",
                [@client, invoice],
                class: "btn btn-outline-danger",
                method: :delete,
                data: { turbo_confirm: "¿Seguro que quieres eliminar el Servicio?" } %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row my-5">
    <div class="col-6">
      <h2>Tickets</h2>
    </div>

    <div class="col-6 text-end">
      <%= link_to "Nuevo Ticket", new_client_ticket_path(@client), class: "btn btn-outline-light" %>
    </div>
  </div>

  <% @tickets.each do |ticket| %>
    <div class="card bg-black text-secondary mb-5">
      <h3 class="card-header"><%= ticket.state %></h3>
      <div class="card-body row">
        <p class="card-text">Nivel de Prioridad: <strong><%= ticket.priority_level %></strong></p>
        <p class="card-text">Descripción: <strong><%= ticket.description %></strong></p>
        <div class="col-6">
          <%= link_to "Editar ticket", edit_client_ticket_path(@client, ticket), class: "btn btn-outline-secondary" %>
        </div>
        <div class="col-6 text-end">
          <%= button_to "Eliminar ticket",
                [@client, ticket],
                class: "btn btn-outline-danger",
                method: :delete,
                data: { turbo_confirm: "¿Seguro que quieres eliminar el Ticket?" } %>
        </div>
      </div>
    </div>
  <% end %>
</div>