config/routes.rb
Rails.application.routes.draw do
  resources :service_packages
  get "reports/monthly_income_report"

  resources :clients do
    resources :invoices do
      resources :payments
    end
    resources :tickets
  end

  get "all_invoices", to: "invoices#general_index"

  devise_for :users

  get "servicios", to: "statics#services"
  get "preguntas_frecuentes", to: "statics#frequent_questions"
  get "contáctanos", to: "statics#contact"
  get "nosotros", to: "statics#about_us"

  get "inicio", to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :invoice
  validates :paid_at, presence: { message: "no puede estar vacio" }
  validates :amount, presence: { message: "no puede estar vacio" }
  validates :method, presence: { message: "no puede estar vacio" }

  after_save :add_payment_to_invoice
  after_destroy :remove_payment_from_invoice

  private
  def add_payment_to_invoice
    invoice.set_payment_status
    invoice.save
  end

  def remove_payment_from_invoice
    invoice.reset_payment_status
    invoice.save
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client
  before_action :set_invoice
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @payments = @invoice.payments.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = @invoice.payments.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to client_invoice_payment_path(@client, @invoice, @payment), notice: "El Pago fue realizado exitosamente." }
        format.json { render :show, status: :created, location: [@invoice, @payment] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to client_invoice_payment_path(@client, @invoice, @payment), notice: "El Pago fue actualizado exitosamente." }
        format.json { render :show, status: :ok, location: [@invoice, @payment] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy!

    respond_to do |format|
      format.html { redirect_to client_invoice_path(@client, @invoice), notice: "El Pago fue eliminado exitosamente." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:client_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_invoice
    @invoice = @client.invoices.find(params[:invoice_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = @invoice.payments.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:paid_at, :amount, :method, :notes, :invoice_id)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: [@client, @invoice, payment]) do |form| %>
  <% if payment.errors.any? %>
    <div class="text-danger">
      <h2><%= pluralize(payment.errors.count, "error") %> Se han producido los siguientes errores:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :paid_at, "Pagado el", class: "form-label" %>
  <%= form.date_field :paid_at, class: "form-control mb-3" %>

  <%= form.label :amount, "Monto", class: "form-label" %>
  <%= form.number_field :amount, class: "form-control mb-3" %>

  <%= form.label :method, "Método de pago", class: "form-label" %>
  <%= form.text_field :method, class: "form-control mb-3" %>

  <%= form.label :notes, "Notas", class: "form-label" %>
  <%= form.text_area :notes, class: "form-control mb-3" %>

  <%= form.label :invoice_id, class: "form-label" %>
  <%= form.text_field :invoice_id, class: "form-control mb-3" %>

  <button type="submit" class="btn btn-primary"><%= yield(:button) %></button>
<% end %>

app/views/payments/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-2 offset-sm-4">
      <h1>Editar Pago</h1>
    </div>

    <div class="col-2 text-end">
      <%= link_to "Regresar al Pago", client_invoice_payment_path(@client, @invoice, @payment), class: "btn btn-outline-light" %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-4">
      <% provide(:button, "Editar")%>
      <%= render "form", payment: @payment %>
    </div>
  </div>
</div>

app/views/payments/index.html.erb
<div class="container">
  <div class="row mb-4">
    <div class="col-6">
      <h2>Listado de Pagos</h2>
    </div>

    <div class="col text-end">
      <div class="btn-group">
        <%= link_to "Nuevo Pago", new_client_invoice_payment_path, class: "btn btn-outline-light rounded-end me-2" %>
        <%= link_to "Regresar a la factura", client_path(@client, anchor: "invoice"), class: "btn btn-outline-light rounded-start" %>
      </div>
    </div>
  </div>

<table class="table table-secondary table-hover table-responsive table-striped text-center">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Pagado el día</th>
        <th scope="col">Monto</th>
        <th scope="col">Método de Pago</th>
        <th scope="col">Anotaciones</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @payments.each do |payment| %>
        <tr>
          <th scope="row"> <%= payment.id %><br></th>
          <td>
            <%= payment.paid_at.to_fs(:long) %>
          </td>
          <td><%= number_to_currency payment.amount %></td>
          <td><%= payment.method %></td>
          <td><%= payment.notes %></td>
          <td>
            <%= link_to "Ver Pago",
                  [@client, @invoice, payment],
                  class: "link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/payments/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-2 offset-sm-4">
      <h1>Realizar Pago</h1>
    </div>

    <div class="col-2 text-end">
      <%= link_to "Regresar a la factura", client_invoice_path(@client, @invoice), class: "btn btn-outline-light" %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-4">
      <% provide(:button, "Realizar Pago") %>
      <%= render "form", payment: @payment %>
    </div>
  </div>
</div>

app/views/payments/show.html.erb
<div class="container">
  <div class="row mb-4">
    <div class="col-6">
      <h2>Pago</h2>
    </div>
    <div class="col text-end">
      <div class="btn-group">
        <%= link_to "Regresar a la factura", client_invoice_path(@client, @invoice), class: "btn btn-outline-light rounded-end me-3" %>
        <%= link_to "Listado de Pagos", client_invoice_payments_path, class: "btn btn-outline-light rounded-start" %>
      </div>
    </div>
  </div>

  <div class="card bg-black text-secondary mb-5">
    <h3 class="card-header">
      <p class="card-text">Pagado el día: <strong><%= @payment.paid_at.to_fs(:long) %></strong></p>
    </h3>
    <div class="card-body row">
      <p class="card-text">Monto del Pago: <strong><%= number_to_currency @payment.amount %></strong></p>
      <p class="card-text">Método de Pago: <strong><%= @payment.method %></strong></p>
      <p class="card-text">Anotaciones: <strong><%= @payment.notes %></strong></p>
      <div class="col-6">
        <%= link_to "Editar Pago", edit_client_invoice_payment_path(@client, @invoice, @payment), class: "btn btn-outline-light" %>
      </div>
      <div class="col-6 text-end">
        <%= button_to "Eliminar Pago",
              [@client, @invoice, @payment],
              class: "btn btn-outline-danger",
              method: :delete,
              data: { turbo_confirm: "¿Seguro que quieres eliminar este Pago?" } %>
      </div>
    </div>
  </div>
</div>